drop materialized view homepage;
drop materialized view timeline;
drop table appuser;
drop table website_admin;
drop table hobby;
drop table post;
drop table status;
drop table page;
drop table page_keyword;
drop table usergroup;
drop table message;
drop table about;
drop table tags;
drop table follower;
drop table comment;
drop table reaction;
drop table friend;
drop table likes;
drop table private_chat;
drop table group_chat;
drop table member;
drop table page_admin;
drop table group_admin;
